name: Build and Deploy

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build and publish the image
        run: |
          docker login --username do-map --password ${{ secrets.GH_PAT }} ghcr.io
          docker build ./Server/ -t ghcr.io/domap-fr/porfolio:lts
          docker push ghcr.io/domap-fr/porfolio:lts
  deploy:
    runs-on: ubuntu-latest
    name: Deploy to production server
    steps:
      - uses: actions/checkout@v4
      - name: login to ghcr.io
        run: |
          echo ${{ secrets.GH_PAT }} | docker login --username do-map --password-stdin ghcr.io
      - name: install ssh keys
        run: |
          install -m 600 -D /dev/null ~/.ssh/id_rsa
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts
      - name: connect and pull
        run: |
          sudo apt-get install sshpass
          sshpass -p "${{ secrets.SSH_PASS }}" ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} 'cd ${{ secrets.WORK_DIR }} && docker-compose pull && docker-compose up -d && exit'
      - name: cleanup
        run: |
          rm ~/.ssh/id_rsa
